microsoft/TypeScript-Node-Starter

README.md
package-lock.json
src/controllers/user.ts

added package-lock for npm5 and fixed bug with flash messages

---

.vscode/launch.json
.vscode/tasks.json

Added `build` `preLaunchTask` for debug configuration

---

.vscode/launch.json
README.md
package-lock.json
package.json

- Attach debug configuration
- Scripts: debug, serve-debug, watch-debug
- Readme

add attach debug configuration

---

README.md

seemed like that instruction was missing

add the line to compile dist folder

---

README.md

As mentioned in: https://git.io/vNfiL
Thanks!

Add memo about VSCode suggested extensions to README

---

README.md
package.json
src/types/lusca.d.ts

Definitely easier to maintain,
Thanks!

Replace Lusca definition file with @types/lusca

---

src/public/css/lib/bootstrap/_button-groups.scss
src/public/css/lib/bootstrap/_forms.scss
src/public/css/lib/bootstrap/_input-groups.scss
src/public/css/lib/bootstrap/_panels.scss
src/public/css/lib/bootstrap/_scaffolding.scss
src/public/css/lib/bootstrap/_theme.scss
src/public/css/lib/bootstrap/_variables.scss
src/public/css/lib/bootstrap/bootstrap.scss
src/public/css/lib/bootstrap/mixins/_tab-focus.scss

Mostly small SASS source files updates, but that counts
Thanks!

Update Bootstrap from 3.3.6 to 3.3.7

---

views/account/profile.pug
views/api/facebook.pug
views/api/index.pug
views/partials/header.pug

These are non visual-only or not decorative-only hence
context information added to alts
The content retrieval sorted on what's most frequently available in given context (e.g. name > username or name > email > id), etc.
Thanks!

Add missing alt attr to non-decorative images

---

README.md

Added db folder creation command and permission config.
Thanks @Bigbrd

Update README.md with MongoDB config

---

package-lock.json
package.json

Update ShellJS version

---

src/models/User.ts

declare function signature only once
not completely sure about this but the idea makes sense, maybe there is a cleaner way to do this?

use same signature for model function & ts type

---

src/controllers/user.ts

Fix Error: Unknown authentication strategy "local"

---

src/config/passport.ts
src/controllers/api.ts
src/controllers/contact.ts
src/controllers/home.ts
src/controllers/user.ts

Every variable that wouldn't change should be declared as const for safety reasons.
We can assume that function expressions would not be overwritten.

Changed function expressions declarations from let to const

---

README.md

Closes #145 - handles all the rebasing etc

Improvements to the README from PR #145

---

package-lock.json
package.json
src/types/express-flash.d.ts

There is existing @types definition for express-flash. Let's use it and
just augment a method required by the existing code to please compiler.
Thanks!

Simplify augmented module for express-flash

---

package-lock.json
package.json

- `request`
- `request-promise`
`request` first appeared as part of initial commit but it seems to be
left-over from non commited implementation:
https://git.io/JvgNV
`request-promise` was added in different PR but it seems without related
code:
https://git.io/JvgN6
/cc @naknode
Thanks!

:heavy_minus_sign: remove unused dependencies. Closes #272

---

README.md

This is still really high up on search engines as a key result, but there are many good templates in https://www.typescriptlang.org/docs/home which I maintain (with this being _one_ of them )
This sends folks over to that if they're just looking to get something started

Update README.md to frame what this repo is

---

README.md

Documentation link was broken without .html
`The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.`

Update README.md - fix documentation link

---

src/controllers/api.ts
src/controllers/contact.ts
src/controllers/home.ts
src/controllers/user.ts

Using JSdocs labels for improved code documentation when hovering on function.
For more info [jsdoc cheetsheet](https://devhints.io/jsdoc) or [jsdoc.app](https://jsdoc.app/tags-type.html)

Added JSdocs comment labels for improved code documentation

---

.travis.yml

Should fix issues with failing CI checks on updated packages.
/cc @samal-rasmussen
Thanks!

[ci] update Node version for Travis build

---

README.md

- Replaced section about mLab with MongoDB Atlas
- Updated page internal link to SendGrid to work again (anchor was broken)

Update section about hosted MongoDB instance #207

---

package-lock.json
package.json
src/app.ts

Upgrade the connect-mongo package to v4 #324

---

src/config/passport.ts

This fixes issue with failing pages
/cc @klemensz
Fixes #323

fix(323): wrong reference used

---

package-lock.json
package.json

This updates some deps to remove high security warnings from NPM audits.
Thanks!

update(deps): update dependencies

---

package-lock.json
package.json

- fix resolution for @types/bson to 4.0.5
- bump Node types to one with 'Blob' package introduced as global object
- minimal Node engine version set to v14 (to match @types/node version resolution)
/cc @mozgbrasil
Fixes #349

fix(deps): fix failing yarn builds
