microsoft/TypeScript-Node-Starter

- package.json
npm script `serve` was orphant. Replaced it with `nodemon dist/server.js` from the end of `watch` script and placed it's execution in the end of `watch` script to remove duplication at all.
> Removed duplication in npm scripts `serve` and `watch`

- package.json
- src/config/passport.ts
- src/controllers/api.ts
- src/controllers/contact.ts
- src/controllers/home.ts
- src/controllers/user.ts
- src/models/User.ts
fix error TS2559: Type '4' has no properties in common with type 'MinMaxOptions'.
fix error TypeScript-Node-Starter/src/controllers/api.ts[6, 9]: missing whitespace, 8 files
fix bugs of issue 15
> fit  bugs of issue 15 and some other bugs caused by tslint

- copyStaticAssets.js
- src/config/passport.ts
- src/controllers/api.ts
- src/controllers/contact.ts
- src/controllers/home.ts
- src/controllers/user.ts
This pull request fixes the problem of the current version that when files are being copied to the `dist` folder, some folders will be copied inside another folder with the same name.
> fix: copying issues

- .vscode/tasks.json
I noticed the .vscode/tasks.json file was still using the version 0.1.0 format, so I replaced it with a file that executes the same task using the new 2.0.0 version:
https://code.visualstudio.com/docs/editor/tasks#_convert-from-010-to-200
> Bump tasks.json version from 0.10 to 2.00. Add default build task.

- .vscode/launch.json
- .vscode/tasks.json
This PR simply updates the debug configuration's `preLaunchTask` setting, in order to accomodate the new auto-detection of NPM scripts. Without this change, I receive the following error when trying to debug this starter using VS Code 1.15:
Alternatively, we could update the `tasks.json` file to set the build task's `taskName` property to `build`. However, the `taskName` property is now deprecated (in favor of `label`), and the build task doesn't really need a `label` anyways since it's only being defined via `tasks.json` in order to configure it as the default build task.
> Update debug configuration

- test/api.test.ts
- test/app.test.ts
- test/contact.test.ts
- test/home.test.ts
- test/user.test.ts
Though tests can be run since the testing files won't need to go through tslint, but warnings will  appear on all the testing files regarding `describe` and `it`. I have applied a simple fix by simply `import {} from 'jest';`
app.test.ts
> fix: fix lint warnings for test files

- README.md
The docs and tsconfig.js both say `sourceMap`, not `sourceMaps`.
> Removed extra "s" in sourceMap compilerOptions

- README.md
- jest.config.js
- package.json
extract jest config to a separate file, as it's a better way for separation of concern.
> feat: move jest config to external file

- .vscode/extensions.json
The VSCode CosmosDB supports locally installed MongoDB servers
(and lot of other things and features).
It seems reasonable to offer that extension to project users.
Thanks!
> Add VSCode CosmosDB extension recommendation

- README.md
The description for npm start is not correct. It does not do a full build. Changed the description in the table to reflect what the actual behavior is.
> changed description of npm start

- views/layout.pug
- views/partials/footer.pug
This commit:
- removes obsolate frameborder scrolling attributes from iframe
replacing them with inline style
- correct values for inline width/height for embedded iframe
- adds lang attr
- sort order of the head elements: see e.g. https://git.io/vNfEF
- update GA insline script to their shortest version and async/deferred script,
see: https://git.io/vNfuU
- use unbuffered comments so there is no output in transpiled html
Thanks!
> Update view markups for HTML5 compatibility

- .gitignore
A simple one: This allows to avoid manual removal of output after  test runs
from pending git changes
Thanks!
> Do not store output from coverage tests in repo

- .env.example
- .gitignore
- .vscode/settings.json
- README.md
- package-lock.json
- package.json
- src/app.ts
- src/util/logger.ts
- src/util/secrets.ts
- views/layout.pug
- views/partials/footer.pug
This PR is primarily for adding guidance on publishing the app. Notable changes:
- Added new sections to the README
- Replaced logger with Winston
- Updated how env vars and secrets are managed
> Add Azure publish support

- package.json
Versions of lodash before 4.17.5 are vulnerable to prototype pollution: https://nodesecurity.io/advisories/577
> prototype pollution

- package-lock.json
It looks like the lock file got out of date. I re-ran it with npm 6 to get things back in sync so `npm ci` is happy again.
> tests: Travis seems unhappy. This should resolve that.

- jest.config.js
Resolves a warning running tests — this was consistently reproducible both locally and in CI. See e.g.,
[the latest Travis build](https://travis-ci.org/microsoft/TypeScript-Node-Starter/builds/533095625):
```console
ts-jest[backports] (WARN) "[jest-config].globals.ts-jest.tsConfigFile" is deprecated, use "[jest-config].globals.ts-jest.tsConfig" instead.
```
Simple one-line fix. 👌
> fix(jest): Update deprecated ts-jest config option.

- .gitignore
- src/util/secrets.ts
this is more of a minor change but the error message is mis-leading when using `.env`. 
`MONGODB_URI_LOCAL` is used in all other environment other than production.
```sh
export const MONGODB_URI = prod ? process.env["MONGODB_URI"] : process.env["MONGODB_URI_LOCAL"];
```
Therefore, It should notify the user to set `MONGODB_URI_LOCAL` rather than `MONGODB_URI` if it is not **production**.
> Add better logging when setting custom env var using .env

- README.md
Line 67 ("Change 'MongoLab's Website' to 'mLab's Website'.")
Line 107 (Removed 'for')
Line 146 (Added an 's' to project)
Line 191 (Grammar Changes)
Line 232 (Missing 's' on 'define')
Line 366 (Added comma before 'when configured correctly')
> Some grammatical changes to README.md

- src/models/User.ts
Using default value for size param in gravatar method is more convenient.
> Change size existence check to default value

- README.md
the markdown code was present, but there was no actual link to follow.
> added link to vscode TSLint extention in readme

- package-lock.json
This removes NPM audit warnings, which seems to be raised by the older
version of the lock file.
The `npm install` was showing a red herring warning:
```bash
audited 865018 packages in 8.506s
found 12708 high severity vulnerabilities
```
With this commit the same outputs from the rebuid `package-lock.json`:
```bash
audited 877521 packages in 9.46s
found 0 vulnerabilities
```
This one was regenerated with NPM v6.9.0 (Node v10.*)
Thanks!
> Update NPM lock down file.

- .travis.yml
This fixes the YAML related extensions errors in VSCode, as the
schema for .travis.yml requires a quoted strings here:
https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#specifying-nodejs-versions
Thanks!
> Specify NodeJS version as strings in Travis configuration

- README.md
The configuration for Jest tests with support fo the TypeScript files
are now handled by Jest configuration file.
Thanks!
> :memo: remove reference to legacy file. Closes #190

- package.json
fix lint error
```
PS> npm run lint                                                                                                        
> express-typescript-starter@0.1.0 lint C:\Users\JipingWang\source\repos\api
> tsc --noEmit && eslint '*/**/*.{js,ts}' --quiet --fix
Oops! Something went wrong! :(
ESLint: 5.16.0.
No files matching the pattern "'*/**/*.{js,ts}'" were found.
Please check for typing mistakes in the pattern.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! express-typescript-starter@0.1.0 lint: `tsc --noEmit && eslint '*/**/*.{js,ts}' --quiet --fix`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the express-typescript-starter@0.1.0 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log …
```
> fix lint error

- .eslintrc
- jest.config.js
- package.json
- src/app.ts
- Disables the rules `explicit-function-return-type` and `no-explicit-any` which causes many warnings for the current codebase.
- Expand linting to include root directory as well
> Fix lint warnings

- src/app.ts
See: https://mongoosejs.com/docs/deprecations.html#ensureindex
Thanks!
> Use update indexes access in Mongoose configuration. Fixes #225

- .eslintrc
unused vars with "error" extremely annoying for developement;
"any" and inferrable types could and should be avoided, "warn" would make sense.
> eslint, no any, no inferrable types, unused vars - warning

- README.md
Updating the readme to mention the change in macOS and offer an alternative location for Mongo's data/db directory.
> Updated readme to instruct to create Mongo's data/db directory under the home directory in macOS 10.15

- src/controllers/contact.ts
- src/controllers/user.ts
I ran into #231 earlier and fixed it for my own app. I don't know if this is the best way to run the validations, but it was a quick & easy fix.
> Update source code to work with express-validator 6.x. Fixes #231

- package-lock.json
- package.json
This updates Jest and its dependencies, removing the warning about the left-pad module deprecation.
Thanks!
Reference to the upstream issue:
https://github.com/facebook/jest/issues/8516
> :arrow_up: upgrade Jest version

- .vscode/settings.json
[dbaeumer.vscode-eslint](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint) has deprecated `eslint.autoFixOnSave` among other changes/improvements in version 2.0.4.
Updated `settings.json` to fix the following errors:
- The setting is deprecated. Use editor.codeActionsOnSave instead with a source.fixAll.eslint member.
- Auto Fix is enabled by default. Use the single string form.
> vscode-eslint v2 settings patch

- .env.example
- README.md
- Added `SENDGRID_USERNAME`, `SENDGRID_PASSWORD`, and `PORT` to `.env.example`.
- Added SendGrid account configuration documentation to `README.md`.
> Added SendGrid Username, Password, Port to .env.example

- .github/workflows/ci.yml
- .github/workflows/nodejs.yml
- README.md
Added a GitHub Actions Workflow with a matrix strategy for Node.js 8.x, 10.x, and 12.x and across Ubuntu, MacOS, and Windows with support for node_modules caching to improve speed.
> Added GitHub Actions CI Workflow

- .env.example
Fixed typo in SendGrid comment: s/her/here/
> Fixed typo in SendGrid comment

- package-lock.json
- package.json
This version bump should fix issue with `node-sass` installation on some
systems.
Tested on Win 10.
Thanks!
Closes #165
> fix(node-sass): bump version

- package-lock.json
- package.json
Upgrade 'concurrently' pacakge since npm audit shows it as a high treat vulnerability.
I tested the two scripts that are using it (watch, watch-debug), seems to have no effect (good).
> Update deps: concurrently (#311) [edited]

- README.md
- jest.config.js
This removes warnings about deprecated configuration option:
```text
tsConfig` is depecrated and will be removed in ts-jest 27
```
https://github.com/kulshekhar/ts-jest/commit/8fec6816e1b6009c4ba9b41f111c896d3c2fc3f5
Thanks!
> update(ts-jest): update `ts-config` configuratin for 6.27
